config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#show'
  get 'auth/google_oauth2/callback', controller: :sessions, action: :create
  get 'auth/failure', to: redirect('/')
  get '/logout', controller: :sessions, action: :destroy
  delete '/logout', controller: :sessions, action: :destroy
  resources :users, only: %i[show edit update]
  resources :trips do
    patch '/vote', to: 'trips/votes#update'
    patch '/vote_status', to: 'trips/votes#update_status'
  end
  namespace :trips do
    resources :riders, only: :create
  end
  resources :resorts, only: [:index, :show]
  resources :friendships, only: :create
  resources :resort_options, only: :create
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  private

  def current_user
    current_user ||= UserFacade.user_get(session[:user_id]) if session[:user_id]
  end
end

app/controllers/friendhips_controller.rb
class FriendshipsController < ApplicationController
  def create
    require 'pry'; binding.pry
    friend = User.find_by(email: params[:email])
    if friend
      current_user.friendships.create(friend: friend)
    else
      flash[:error] = 'Invalid email. Please try again.'
    end
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def create
    friendship = FriendshipFacade.get_friend(friendship_params)
    redirect_to user_path(current_user.id)
  end

  private

  def friendship_params
    {
      email: params[:email],
      user_id: current_user.id
    }
  end
end

app/controllers/resort_options_controller.rb
class ResortOptionsController < ApplicationController
  def create
    option_params = { trip_id: params[:trip_id],
                      resort_id: params[:resort_id],
                      resort_name: params[:name]}
    TripFacade.create_resort_option(option_params)
    redirect_to trip_path(params[:trip_id])
  end
end

app/controllers/resorts_controller.rb
class ResortsController < ApplicationController
  def index
    @resorts = (ResortFacade.resorts_by_state(params[:state]) if params[:state].present?)
  end

  def show
    @resort = ResortFacade.resort_by_id(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    access_token = request.env['omniauth.auth']
    user = UserFacade.user_auth(access_token[:info][:email], access_token[:info][:name])
    session[:user_id] = user.id
    unless user.nil?
      flash[:success] = 'Login Successful'
      redirect_to user_path(user.id)
    end
  end

  def destroy
    session.clear
    if current_user.nil?
      flash[:success] = 'Logout successful'
      redirect_to root_path
    end
  end
end

app/controllers/trips/riders_controller.rb
class Trips::RidersController < ApplicationController
  def create
    rider_params = {
      user_id: params[:user_id],
      trip_id: params[:trip_id],
      host: params[:host],
      driver: params[:driver],
      budget: params[:budget]
    }
    TripFacade.create_rider(rider_params)
    redirect_to trip_path(params[:trip_id])
  end
end

app/controllers/trips/votes_controller.rb
class Trips::VotesController < ApplicationController
  def update
    vote_params = {
      user_id: params[:user_id],
      resort_id: params[:resort_id]
    }
    TripFacade.vote(params[:trip_id], vote_params)
    redirect_to trip_path(params[:trip_id])
  end

  def update_status
    status_params = {
      open: params[:open]
    }
    TripFacade.close_vote(params[:trip_id], status_params)
    redirect_to trip_path(params[:trip_id])
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  def new; end

  def create
    @trip = TripFacade.create_trip(trip_params)
    unless @trip.nil?
      flash[:success] = 'Trip created successfully'
      redirect_to trip_path(@trip.id)
    end
  end

  def show
    @user = UserFacade.user_get(current_user.id)
    @trip = TripFacade.trip_get(params[:id])
    @resorts = (ResortFacade.resorts_by_state(params[:state]) if params[:state].present?)
    @resort = ResortFacade.resort_by_id(@trip.resort_id) if @trip.resort_id
  end

  def edit
    @trip = TripFacade.trip_get(params[:id])
  end

  def update
    trip = TripFacade.update_trip(params[:id], trip_params)
    redirect_to trip_path(trip.id)
  end

  def destroy
    TripFacade.destroy_trip(params[:id])
    redirect_to user_path(current_user.id)
  end

  private

  def trip_params
    {
      name: params[:name],
      start_date: params[:start_date],
      end_date: params[:end_date],
      resort_id: params[:resort_id],
      resort_name: params[:resort_name],
      user_id: params[:user_id]
    }
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    current_user
    # require "pry"; binding.pry
    # use response codes to get flash messages
  end

  def edit
    current_user
  end

  def update
    UserFacade.user_update(current_user.id, updated_attributes)
    redirect_to user_path(current_user.id)
  end

  private

  def updated_attributes
    {
      name: params[:name],
      address: params[:address],
      ski_pass: params[:ski_pass],
      ski_or_board: params[:ski_or_board],
      exp_level: params[:exp_level],
      emergency_name: params[:emergency_name],
      emergency_number: params[:emergency_number]
    }
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def show; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/states_helper.rb
module StatesHelper
  def us_states
  [
    ['Alabama', 'AL'],
    ['Alaska', 'AK'],
    ['Arizona', 'AZ'],
    ['Arkansas', 'AR'],
    ['California', 'CA'],
    ['Colorado', 'CO'],
    ['Connecticut', 'CT'],
    ['Delaware', 'DE'],
    ['Florida', 'FL'],
    ['Georgia', 'GA'],
    ['Hawaii', 'HI'],
    ['Idaho', 'ID'],
    ['Illinois', 'IL'],
    ['Indiana', 'IN'],
    ['Iowa', 'IA'],
    ['Kansas', 'KS'],
    ['Kentucky', 'KY'],
    ['Louisiana', 'LA'],
    ['Maine', 'ME'],
    ['Maryland', 'MD'],
    ['Massachusetts', 'MA'],
    ['Michigan', 'MI'],
    ['Minnesota', 'MN'],
    ['Mississippi', 'MS'],
    ['Missouri', 'MO'],
    ['Montana', 'MT'],
    ['Nebraska', 'NE'],
    ['Nevada', 'NV'],
    ['New Hampshire', 'NH'],
    ['New Jersey', 'NJ'],
    ['New Mexico', 'NM'],
    ['New York', 'NY'],
    ['North Carolina', 'NC'],
    ['North Dakota', 'ND'],
    ['Ohio', 'OH'],
    ['Oklahoma', 'OK'],
    ['Oregon', 'OR'],
    ['Pennsylvania', 'PA'],
    ['Rhode Island', 'RI'],
    ['South Carolina', 'SC'],
    ['South Dakota', 'SD'],
    ['Tennessee', 'TN'],
    ['Texas', 'TX'],
    ['Utah', 'UT'],
    ['Vermont', 'VT'],
    ['Virginia', 'VA'],
    ['Washington', 'WA'],
    ['West Virginia', 'WV'],
    ['Wisconsin', 'WI'],
    ['Wyoming', 'WY']
  ]
  end
end

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>Snowmigo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <br>
    <div class='container'>
      <%= render 'shared/flash' %>
      <%= yield %>
    </div>
    <br>
    <br>
    <footer></footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
</html>

app/views/resorts/index.html.erb
<body class='resort-index'
  <h3>Resorts</h3>
  <%= render 'shared/resort_search', path: resorts_path %>
</body>

app/views/resorts/show.html.erb
<body class="resorts">
  <div class="container">
    <div class="row">
      <div class="col-4">
        <br>
        <div class="card" style="width: 18rem;">
          <img src="<%= @resort.logo %>" class="card-img-top" alt="<%= @resort.name %>">
          <ul class="list-group list-group-flush">
            <li class="list-group-item" style="background-color: #E7ECEF;">
              <h5 class="card-title"><%= @resort.name %></h5>
              <p class="card-text">Mask Required:
                <%= @resort.mask_required %></p>
            </li>
            <li class="list-group-item" style="background-color: #E7ECEF;">
              <div id="<%= @resort.id %>-snow">
                <ul>
                  <strong>Snow Conditions</strong>
                  <li>New Snow:<%= @resort.new_snow %>
                    in</li>
                  <li>Base Depth:
                    <%= @resort.base_depth %>
                    in</li>
                  <li>Snow Condition:
                    <% if @resort.snow_condition == '' %>
                      <p>No snow</p>
                    <% else %>
                      <%= @resort.snow_condition %></li>
                  <% end %>
                </ul>
              </div>
            </li>
            <li class="list-group-item" style="background-color: #E7ECEF;">
              <div id="<%= @resort.id %>-features">
                <ul>
                  <strong>Resort Features</strong>
                  <li>Open Lifts:
                    <% if @resort.open_lifts == nil %>
                      <p>0</p>
                    <% else %>
                      <%= @resort.open_lifts %></li>
                  <% end %>
                  <li>Open Trails:
                    <%= @resort.open_trails %></li>
                  <li><%= link_to 'Trail Map', @resort.trail_map %></li>
                </ul>
              </div>
            </li>
          </ul>
        </div>
      </div>
      <div class="col-5">
        <div id="<%= @resort.id %>-weather">
          <br>
          <br>
          <table class="table">
            <thead>
              <tr>
                <th scope="col">Today's Forecast</th>
                <th scope="col"></th>
                <th scope="col">Snowfall</th>
                <th scope="col">Temp</th>
                <th scope="col">Wind</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <div id="morning-weather">
                  <th scope="row">Morning</th>
                  <td>
                    <img src="<%= @resort.morning_weather[:weather_icon] %>" alt="<%= @resort.morning_weather[:weather] %>">
                  </td>
                  <td>
                    <% if @resort.morning_weather[:snowfall] == nil %>
                      <p>0 in</p>
                    <% else %>
                      <%= @resort.morning_weather[:snowfall] %>
                    <% end %>
                  </td>
                  <td>
                    <%= @resort.morning_weather[:temp] %>
                    Fahrenheit
                  </td>
                  <td>
                    <%= @resort.morning_weather[:wind] %>
                    mph
                  </td>
                </div>
              </tr>
              <tr>
                <div id="noon-weather">
                  <th scope="row">Noon</th>
                  <td>
                    <img src="<%= @resort.noon_weather[:weather_icon] %>" alt="<%= @resort.noon_weather[:weather] %>">
                  </td>
                  <td>
                    <% if @resort.noon_weather[:snowfall] == nil %>
                      <p>0 in</p>
                    <% else %>
                      <%= @resort.noon_weather[:snowfall] %>
                    <% end %>
                  </td>
                  <td>
                    <%= @resort.noon_weather[:temp] %>
                    Fahrenheit
                  </td>
                  <td>
                    <%= @resort.noon_weather[:wind] %>
                    mph
                  </td>
                </div>
              </tr>
              <tr>
                <div id="afternoon-weather">
                  <th scope="row">Afternoon</th>
                  <td>
                    <img src="<%= @resort.afternoon_weather[:weather_icon] %>" alt="<%= @resort.afternoon_weather[:weather] %>">
                  </td>
                  <td>
                    <% if @resort.afternoon_weather[:snowfall] == nil %>
                      <p>0 in</p>
                    <% else %>
                      <%= @resort.afternoon_weather[:snowfall] %>
                    <% end %>
                  </td>
                  <td>
                    <%= @resort.afternoon_weather[:temp] %>
                    Fahrenheit
                  </td>
                  <td>
                    <%= @resort.afternoon_weather[:wind] %>
                    mph
                  </td>
                </div>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</body>

app/views/shared/_flash.html.erb
<% if flash[:success] %>
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= flash[:success] %>
  </div>
<% end %>

<% if flash[:notice] %>
  <div class="alert alert-info alert-dismissible fade show" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= flash[:notice] %>
  </div>
<% end %>

<% if flash[:alert] %>
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= flash[:alert] %>
  </div>
<% end %>

<% if flash[:danger] %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= flash[:danger] %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class='navbar navbar-expand-lg navbar-dark' style="background-color: #113686;" id='navbar'>
  <div class='container-fluid'>
    <% if current_user %>
    <div class='nav-image'>
      <%= image_tag("nav-logo-2.png", style: 'display: block; width: 10%;') %>
    </div>
    <% end %>
    <button class='navbar-toggler' type='button' data-bs-toggle='collapse' data-bs-target='#navbarNav' aria-controls='navbarNav' aria-expanded='false' aria-label='Toggle navigation'>
      <span class='navbar-toggler-icon'></span>
    </button>
    <div class='collapse navbar-collapse' id='navbarNav'>
      <div class='navbar-nav'></div>
      <div class='navbar-nav ms-auto'>
        <% if current_user %>
          <%= link_to 'Dashboard', user_path(current_user.id), class: 'navbar-brand' %>
          <%= link_to 'Search resorts', resorts_path, class: 'navbar-brand' %>
          <%= link_to 'Plan a trip', new_trip_path, class: 'navbar-brand' %>
          <%= link_to 'Logout', logout_path, method: :delete, class: 'navbar-brand' %>
        <% end %>
      </div>
    </div>
  </div>
</nav>

app/views/shared/_resort_search.html.erb
<div id="resorts-search">
  <%= form_with url: path, method: :get, local: true do |f| %>
  <%= f.label :state, 'Search by State:' %>
  <%= f.select :state, options_for_select(us_states) %>
  <%= f.submit 'Search' %>
<% end %>
</div>
<div id="resorts">
<% if @resorts %>
  <ul>
    <div class="row text-center">
      <% @resorts.each do |resort| %>
      <div class="col-sm">
      <div id="resort-<%= resort.id %>">
          <div class="card">
            <img class="card-img-top-thumbnail object-fit: cover" src='<%= resort.logo %>' alt="Logo">
            <div class="card-body d-flex flex-column">
              <h6 class="card-title mt-auto"><%= link_to resort.name, resort_path(resort.id) %></h6>
              <% if path != resorts_path %>
                <%= link_to 'Add to Trip', resort_options_path(resort_id: resort.id, trip_id: @trip.id, name: resort.name), method: :post, class: "btn btn-primary"%>
              <% end %>
            </div>
          </div><br>
        </div>
      </div>
    <% end %>
  </div>
  </ul>
<% else %>
  Please select a State to search for resorts.
<% end %>
</div>

app/views/trips/edit.html.erb
<body class='edit'>
  <div id='box'>
    <%= form_with url: trip_path(@trip.id), method: :patch, local: true do |f| %>
    <div class="form-floating mb-3">
      <%= f.text_field :name, value: @trip.name, class: "form-control", id: "floatingInput2", required: true %>
      <%= f.label "Name your trip!" %>
    </div>
    <br>
    <div class="form-floating mb-3">
      <h6>Start Date</h6>
      <%= f.date_field :start_date, value: @trip.start_date, required: true %>
    </div>
    <div class="form-floating mb-3">
      <h6>End date</h6>
      <%= f.date_field :end_date, value: @trip.end_date, required: true %>
    </div>
    <%= f.submit 'Edit trip!', class: 'btn btn-primary' %>
    <% end %>
  </div>
</body>

app/views/trips/new.html.erb
<body class='new-trip'
<br>
  <div id='box'>
    <%= form_with url: trips_path, method: :post, local: true do |f| %>
    <div class="form-floating mb-3">
      <%= f.hidden_field :user_id, value: current_user.id %>
      <%= f.text_field :name, class: "form-control", id: "floatingInput2" %>
      <%= f.label "Name your trip!" %>
    </div>
    <br>
    <div class="form-floating mb-3">
      <h6>Start Date</h6>
      <%= f.date_field :start_date, required: true %>
    </div>
    <div class="form-floating mb-3">
      <h6>End date</h6>
      <%= f.date_field :end_date, required: true %>
    </div>
    <%= f.submit 'Create trip!', class: 'btn btn-primary' %>
    <% end %>
  </div>
</body>

app/views/trips/show.html.erb
<body class='trip-show'>
  <div class="container">
    <div class="row justify-content-md-center">
      <div id='box'>
        <div class="col col-lg-2">
          <div id='trip-info'>
            <h2><%= @trip.name %></h2>
            <p>
              <b>Dates:</b>
              From
              <%= @trip.format_start_date %>
              to
              <%= @trip.format_end_date %></p>
              <%= link_to "Update trip info", edit_trip_path(@trip.id) %>
              <%= link_to "Delete trip", trip_path(@trip.id), method: :delete %>
            </div>
        </div>
      </div>
    </div>
  </div><br><br>
  <div class="container">
    <div class="row align-items-start">
      <div id='box'>
      <div class="col">
        <h3>Add Friends to Trip:</h3>
        <% @user.friends_to_add(@trip.added_friends).each do |friend| %>
        <div id="friend-<%= friend[1] %>">
          <h6 id="add_friend"><%= friend[0] %></h6>
          <h6><%= button_to "Add", trips_riders_path, params: {user_id: friend[1], trip_id: @trip.id} %></h6>
        </div>
        <% end %><br><br>
        <h3>Added Friends:</h3>
        <% @trip.riders.each do |rider| %>
        <div id="rider-<%= rider[:data][:attributes][:user_id] %>">
          <ul>
            <li><%= rider[:data][:attributes][:rider_name] %></li>
          </ul>
        </div>
        <% end %>
        <% if @trip.vote_status == 'open' %>
      </div>
      <div class="col">
        <h3>Resort Options:</h3>
        <% if @trip.host?(@user.id) %>
        <%= link_to 'Close Voting', trip_vote_status_path(trip_id: @trip.id, open: false), method: :patch, class: "btn btn-primary"%>
        <% end %><br><br>
        <div id="options">
          <% if @trip.options %>
          <ul>
            <div class="row text-center">
              <% @trip.options.each do |option| %>
                <div class="col-sm-6">
                  <div id="option-<%= option[:data][:attributes][:resort_id] %>">
                  <div class="card">
                    <div class="card-body">
                      <h5 class="card-title"><%= link_to option[:data][:attributes][:resort_name], resort_path(option[:data][:attributes][:resort_id]) %></h5>
                      <p class="card-text">Number of Votes:
                        <%= option[:data][:attributes][:vote_count] %></p>
                        <% if @trip.user_vote(@user.id) != option[:data][:attributes][:resort_id] %>
                        <%= link_to 'Vote', trip_vote_path(trip_id: @trip.id, resort_id: option[:data][:attributes][:resort_id], user_id: current_user.id), method: :patch, class: "btn btn-primary"%>
                        <% end %>
                      </div>
                    </div>
                  </div>
                </div>
                <% end %>
              </div>
            </ul>
            <% else %>
            Please add resorts below.
            <% end %>
          </div>
          <% else %>
          <h3>Resort Chosen:</h3>
          <div class="row text-center">
            <div class="col-sm-8">
              <div id="chosen_option">
                <div class="card">
                  <img class="card-img-top-thumbnail object-fit: cover" src='<%= @resort.logo %>' alt="Logo">
                  <div class="card-body">
                    <h5 class="card-title"><%= link_to @resort.name, resort_path(@resort.id) %></h5>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <% end %>
        </div>
        <div class="col">
          <h3>Add Resorts:</h3>
          <%= render 'shared/resort_search', path: trip_path(@trip.id) %>
        </div>
        </div>
    </div>
  </div>
</body>

app/views/users/edit.html.erb
<body class='edit'>
  <div id='box'>
    <%= form_with url: user_path(current_user), method: :patch, local: true do |f| %>
    <div class="form-floating mb-3">
      <%= f.text_field :name, class: "form-control", id: "floatingInput2", value: current_user.name %>
      <%= f.label :name %>
    </div>
    <div class="form-floating mb-3">
      <%= f.text_field :address, class: "form-control", id: "floatingInput2", value: current_user.address %>
      <%= f.label :address %>
    </div>
    <div class="form-floating mb-3">
      <%= f.text_field :emergency_name, class: "form-control", id: "floatingInput2", value: current_user.emergency_name %>
      <%= f.label :emergency_name %>
    </div>
    <div class="form-floating mb-3">
      <%= f.text_field :emergency_number, class: "form-control", id: "floatingInput2", value: current_user.emergency_number %>
      <%= f.label :emergency_number %>
    </div>
    <div>
      <h6>Ski Pass</h6>
      <%= f.select :ski_pass, ['', 'Epic', 'Ikon', 'Other'], selected: current_user.ski_pass %>
    </div>
    <br>
    <div>
      <h6>Ski or Snowboard?</h6>
      <%= f.select :ski_or_board, ['', 'Ski', 'Snowboard', 'Both'], selected: current_user.ski_or_board %>
    </div>
    <br>
    <div>
      <h6>Experience Level</h6>
      <%= f.select :exp_level, ['', 'Beginner', 'Intermediate', 'Advanced', 'Expert'], selected: current_user.exp_level %>
    </div>
    <br>
    <%= f.submit "Update Info" %>
    <% end %>
  </div>
</body>

app/views/users/show.html.erb
<body class="users">
  <div class="container px-0">
    <div class="row gx-5">
      <div class="col">
       <div class="p-3" id="profile-card">
         <br>
          <div class="card" id='user-info' style="width: 18rem;">
            <div class="card-body">
              <h5 class="card-title"><%= current_user.name %></h5>
              <p class="card-text"></p>
            </div>
          <ul class="list-group list-group-flush">
            <li class="list-group-item">Location: <%= current_user.address %></li>
            <li class="list-group-item">Pass Type: <%= current_user.ski_pass %></li>
            <li class="list-group-item">Board or ski: <%= current_user.ski_or_board %></li>
            <li class="list-group-item">Experience Level: <%= current_user.exp_level %></li>
            <li class="list-group-item">Emergency Contact Name: <%= current_user.emergency_name %></li>
            <li class="list-group-item">Emergency Contact Number: <%= number_to_phone(current_user.emergency_number, area_code: true) %></li>
            <li class="list-group-item"><%= link_to "Edit info", edit_user_path(current_user.id) %></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="col">
      <div class="p-3">
        <br>
        <div class="container" id="hosted-events">
          <div id='friend'>
            <h3>Friends<h3/>
            <%= form_with url: friendships_path, local: true do |f| %>
              <%= f.text_field :email, placeholder: 'name@example.com' %>
              <%= f.submit 'Add Friend' %>
            <% end %>
              <% current_user.friends.each do |friend| %>
                <%=  friend[:data][:attributes][:friend_name] %>
              <% end %>
            <%= 'No friends added currently!' if current_user.friends.empty? %>
          </div>
          <br>
          </div>
        </div>
      </div>
    <div class="col">
      <div class="p-3">
        <div id='upcoming-trips'>
          <p><h3>Upcoming Trips</h3><p/>
          <% if current_user.upcoming_trips.empty? %>
            <p>You have no upcoming trips.</p>
          <% else %>
            <% current_user.upcoming_trips.each do |trip| %><br>
              <%= link_to "#{trip[:data][:attributes][:name]}", trip_path(trip[:data][:id]) %><br>
              <%= trip[:data][:attributes][:start_date] %><br>
              <%= trip[:data][:attributes][:end_date] %><br>
            <% end %>
          <% end %>
        </div>
        <div id='past-trips'>
          <p><h3>Past Trips</h3><p/>
          <% if current_user.past_trips.empty? %>
            <p>Go on some trips!<p/>
          <% else %>
            <% current_user.past_trips.each do |trip| %>
              <%= link_to "#{trip[:data][:attributes][:name]}", trip_path(trip[:data][:id]) %><br/>
              <%= trip[:data][:attributes][:start_date] %><br/>
              <%= trip[:data][:attributes][:end_date] %><br/>
            <% end %>
          <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</body>

app/views/welcome/show.html.erb
<body class="welcome">
  <div class="parent-container">
    <div id="box">
      <div class="d-flex flex-column min-vh-100 text-white justify-content-center align-items-center">
        <img src="https://user-images.githubusercontent.com/58535045/141394649-eae10995-e2e8-43be-b616-0b73df4056fd.png"/>
        <div class="row">
          <div class="col-md-3">
            <a class="btn btn-light" href="/auth/google_oauth2/" role="button" style="text-transform:none">
              <img width="20px" style="margin-bottom:3px; margin-right:5px" alt="Google sign-in" src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Google_%22G%22_Logo.svg/512px-Google_%22G%22_Logo.svg.png" />
              Login with Google
            </a>
          </div>
        </div>

        <!-- Minified CSS and JS -->
        <link   rel="stylesheet"
                href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
                integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
                crossorigin="anonymous">
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
                integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
                crossorigin="anonymous">
        </script>
      </div>
    </div>
  </div>
</body>

<a class="oauth-container btn darken-4 white black-text" href="/users/google-oauth/" style="text-transform:none">